### ISSUE TITLE
LightningProvider Required Capabilities Not Documented Here

### ISSUE THREAD

**Issue by CodeChief** [ms-iot/BusProviders#23]
In the ReadMe.md of the Lightning providers you are missing the critical requirement that the "lowLevelDevices" and the other hidden device capability GUID must be added. Otherwise people will just have their correct code (copied from the sample) bomb-out in Managed code without any error message!

It's only documented here:  https://ms-iot.github.io/content/en-US/win10/LightningProviders.htm
https://ms-iot.github.io/content/images/Lightning/update_manifest.png

But really must be added here: https://github.com/ms-iot/BusProviders/blob/develop/Microsoft.IoT.Lightning.Providers/README.md

References:
https://social.msdn.microsoft.com/Forums/en-US/8996072f-2cce-4879-a20d-cb27de8a80eb/direct-memory-mapped-gpio-driver-how

A small change that will help new users a lot. Also whilst you are updating the readme files please add a link to the child readme files from the BusProviders root readme. When people arrive at your GitHub project it just looks like nothing is documented ;-)

**Comment by IoTGirl** [comment]
@msalehmsft review - This can be closed
