### ISSUE TITLE
abs macro in arduino.h violates compiling in release configuration in vs2015

### ISSUE THREAD

**Issue by siochs** [ms-iot/BusProviders#34]
Hi, first I would like to refer to the following location at [msdn forum](https://social.msdn.microsoft.com/Forums/en-US/7537e5fb-a815-45df-ac1f-d12a03c91934/compiling-microsoftiotlightningproviders-in-release-configuration?forum=WindowsIoT).
The abs macro in Arduino.h prevents chrono std library to compile when switching from Debug to Release configuration in Visual Studio 2015. Deleting this macro (#define abs(x) ((x)>0?(x):-(x))) in line 123 abolishes this issue. Thanks

**Comment by MahmoudGSaleh** [comment]
@siochs Thanks for finding this. It'll be fixed in the next version of the SDK

**Comment by MahmoudGSaleh** [comment]
This has been fixed in the latest Lightning Nuget 1.1.0
