### ISSUE TITLE
SPI Bus 1 Select?

### ISSUE THREAD

**Issue by amcelroy** [ms-iot/BusProviders#37]
Howdy,

I can access the SPI0 bus just fine, but also need to access the SPI1 bus on a R Pi 3. This is not an issue using the SpiDevice methods without Lightning. 

Can an example be added or an small note made on how to select other SPI buses?

**Comment by MahmoudGSaleh** [comment]
Currently, SPI1 is not supported with Lightning. We will try to fix that in a future iteration.

**Comment by IoTGirl** [comment]
Closing - Answer was given
