### ISSUE TITLE
Sql Server Dependencies

### ISSUE THREAD

**Issue by jamessdixon** [ms-iot/BusProviders#4]
I forked the repo and brought it local.  When I opened it using VS2015 Ultimate, I get the following error message
<img width="347" alt="capture" src="https://cloud.githubusercontent.com/assets/1394644/9750562/71e2dd2e-5667-11e5-9873-bfad5f9d0ddd.PNG">

**Comment by wldevries** [comment]
This is a common dependency for building C++ projects with Visual Studio.

**Comment by jessekaplan** [comment]
I've not been able to repro this. Can you delete the file and reopen the project? VS will rebuild it and you should be set. 

Thanks,
Jesse

**Comment by IoTGirl** [comment]
Poster has not responded with more detail in over 1 year - closing as stale.
