### ISSUE TITLE
Expose a virtual byte-sized port for GPIO

### ISSUE THREAD

**Issue by mmccullo** [ms-iot/BusProviders#41]
Many applications have need of an 8-bit parallel transfer of I/O. Is it possible to expose at least one virtual "SetPort/ReadPort" command in the GPIO library that would allow reading/writing of 8 pre-selected GPIO lines in parallel?

For many applications the bit-by-bit read/write limitation of the API is too slow.

**Comment by jordanrh1** [comment]
We do not have any plans to implement this feature, but would accept a (well tested) pull request that added this feature to the Wiring library for Windows.

**Comment by IoTGirl** [comment]
Answer given - Closing Issue
