### ISSUE TITLE
Is GpioChangeReader not supported with Lightning ?

### ISSUE THREAD

**Issue by IotLightning** [ms-iot/BusProviders#49]
Hi,

When I try to use the GpioChangeReader with the direct memory mapped driver I get an exception.
This even occurs in the insider preview version : v.10.0.17035.1000
Is it supported in lightning or is it an implementation error on my side ?
When I switch to the inbox driver everything works just fine.

Best regards

**Comment by ooeygui** [comment]
Sorry for the delay in responding. GpioChangeReader is not supported with Lightning (it uses a completely different API). If you need change reader, please use the standard driver.
