### ISSUE TITLE
Project does not compile

### ISSUE THREAD

**Issue by jamessdixon** [ms-iot/BusProviders#5]
After pulling down a forked repo, I tried to compile the 2 CPP projects (PwmPCA9685 & PwmSoftware).  It says it successfully compiles, but no .dll is generated in the .bin folder.  Also, the references from the SamplePWMConsumer project are broken.
<img width="257" alt="capture" src="https://cloud.githubusercontent.com/assets/1394644/9750586/d38abb28-5667-11e5-82a5-96b8e6e35e03.PNG">

Recompiling does not fix it.  Trying to remove and reattach the references also throws an exception.

**Comment by jessekaplan** [comment]
We've not been able to reproduce this problem. You should be able to find the binaries (for an ARM build) in this path: BusProviders-develop\PWM\ARM\Debug

Have you tried creating a new C++/CX project (for desktop)? It's possible this is a configuration issue. 

Thanks,
Jesse

**Comment by ooeygui** [comment]
We cannot repro this issue
